export const FETCH_CONSTANTS = {
  GET_NEWS_SUCCESS: "FETCH_NEWS_SUCCESS",
  GET_NEWS_REQUEST: "FETCH_NEWS_REQUEST",
  GET_NEWS_FAILURE: "FETCH_NEWS_FAILURE",

  GET_CREW_REQUEST: "GET_CREW_REQUEST",
  GET_CREW_SUCCESS: "GET_CREW_SUCCESS",
  GET_CREW_FAILURE: "GET_CREW_FAILURE",

  GET_EVENTS_SUCCESS: "FETCH_EVENTS_SUCCESS",
  GET_EVENTS_REQUEST: "FETCH_EVENTS_REQUEST",
  GET_EVENTS_FAILURE: "FETCH_EVENTS_FAILURE",

  GET_ARTICLES_REQUEST: "GET_ARTICLES_REQUEST",
  GET_ARTICLES_SUCCESS: "GET_ARTICLES_SUCCESS",
  GET_ARTICLES_FAILURE: "GET_ARTICLES_FAILURE",

  GET_INIT_REQUEST: "GET_INIT_REQUEST",
  GET_INIT_SUCCESS: "GET_INIT_SUCCESS",
  GET_INIT_FAILURE: "GET_INIT_FAILURE",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_NAV_REQUEST: "GET_NAV_REQUEST",
  GET_NAV_SUCCESS: "GET_NAV_SUCCESS",
  GET_NAV_FAILURE: "GET_NAV_FAILURE",

  GET_DICTIONARY_REQUEST: "GET_DICTIONARY_REQUEST",
  GET_DICTIONARY_SUCCESS: "GET_DICTIONARY_SUCCESS",
  GET_DICTIONARY_FAILURE: "GET_DICTIONARY_FAILURE",
};
