export const STATE_STEPS_CONTROL = {
  NEXT_STEP: "NEXT_STEP",
  PREVIOUS_STEP: "PREVIOUS_STEP",
  UPDATE_STEPS: "UPDATE_STEPS",
  STEP_BASIC: "STEP_BASIC",
  STEP_UPDATE_USER_INFORMATIONS: "STEP_UPDATE_USER_INFORMATIONS",
};
