[build.environment]
REACT_APP_FIREBASE_API_KEY="AIzaSyDeA-vkmhundm8kLOayfOf36l_svPd-DaU"
REACT_APP_FIREBASE_AUTH_DOMAIN="saro-7b3bb.firebaseapp.com"
REACT_APP_FIREBASE_DATABASE_URL="https://saro-7b3bb-default-rtdb.europe-west1.firebasedatabase.app"
REACT_APP_FIREBASE_PROJECT_ID="saro-7b3bb"
REACT_APP_FIREBASE_STORAGE_BUCKET="saro-7b3bb.appspot.com"
REACT_APP_FIREBASE_MESSAGING_SENDER_ID="353679884634"
REACT_APP_FIREBASE_APP_ID="1:353679884634:web:cf0fb8d3d7a5407ea37363"
REACT_APP_FRIEBASE_APP_MEASURERMENT_ID="G-2XC0XJYK8L"
REACT_APP_TINY_API_KEY="0k5inukmzjqcfmjwc20nxqrkk850ko7k54ef9ap3cnfrg25b"