import * as CONSTANTS from "@utils/constants";

export const stepsTitle = Object.freeze({
  STEP_BASIC: CONSTANTS.STATE_STEPS_CONTROL.STEP_BASIC,
  STEP_UPDATE_USER_INFORMATIONS:
    CONSTANTS.STATE_STEPS_CONTROL.STEP_UPDATE_USER_INFORMATIONS,
});
